# Use an official Python runtime as a parent image
FROM continuumio/miniconda3

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY ./backend /app
COPY ./zeo\+\+-0.3tar.gz /app
COPY ./env/mof_env.yml /app/env/mof_env.yml
COPY ./env/tf_env.yml /app/env/tf_env.yml

# apt get required packages
RUN apt-get update && \
    apt-get install -y --no-install-recommends wget bzip2 ca-certificates gfortran build-essential

# Create conda environments and base env
RUN conda env create -f ./env/mof_env.yml && \
    conda env create -f ./env/tf_env.yml && \
    conda install -c anaconda flask pandas && \
    conda clean -afy && \
    rm -rf /var/lib/apt/lists/*

# Copy the zeo++ program and install it
RUN gunzip zeo\+\+-0.3.tar.gz
RUN tar xvf zeo\+\+-0.3.tar
WORKDIR /app/zeo\+\+-0.3/voro\+\+/src
RUN make
WORKDIR /app/zeo\+\+-0.3/
RUN make
WORKDIR /app


# Make port 80 available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV NAME conda_env

# Run app.py when the container launches
CMD ["python", "backend/app.py"]
