# Set the base image
FROM continuumio/miniconda3
# handle mac m1 architecture
FROM --platform=linux/amd64 ubuntu:20.04

# Set the working directory to /app
WORKDIR /app

# Copy the environment files
COPY ./env/mof_env.yml /app/env/mof_env.yml
COPY ./env/tf_env.yml /app/env/tf_env.yml

# Install gfortran
RUN apt-get update && \
    apt-get install -y --no-install-recommends wget gfortran

# Create the conda environments
RUN conda env create -f /app/env/mof_env.yml
RUN conda env create -f /app/env/tf_env.yml

# Install flask and pandas in base env
RUN conda install -n base -c anaconda flask pandas

# Copy the zeo++ program and install it
COPY ./zeo++-0.3.tar.gz /app/zeo++-0.3.tar.gz
RUN gunzip zeo++-0.3.tar.gz
RUN tar xvf zeo++-0.3.tar
WORKDIR /app/zeo++-0.3/voro++/src
RUN make
WORKDIR /app/zeo++-0.3/
RUN make

WORKDIR /app

# Copy the rest of the application code into the container
COPY . .

# Expose port 5000 for Flask
EXPOSE 5000

# Set the entrypoint command for the container
CMD ["python", "./backend/app.py"]
